"""Repository discovery and lightweight structural indexing."""

from .discovery import (
    BuildCommand,
    RepositoryManifest,
    build_repository_manifest,
    collect_project_instructions,
    discover_instruction_files,
)
from .index import (
    FileRecord,
    IndexSnapshot,
    ParseResult,
    SearchHit,
    StructuralIndex,
    StructuralParser,
    SymbolRecord,
)
from .intelligence import (
    AllowlistedCliExecutable,
    CliOperationCommand,
    EvidenceCompleteness,
    IntelligenceBackendStatus,
    IntelligenceOperation,
    IntelligenceProvenance,
    IntelligenceReadiness,
    ReadOnlyCliBackendConfig,
    ReadOnlySemanticCliAdapter,
    RepositoryEvidence,
    RepositoryIntelligence,
    RepositoryIntelligenceQuery,
    RepositoryIntelligenceResult,
    SemanticBackendDisabledError,
    SemanticCliCommandPlan,
    SemanticExecutionReceipt,
    SemanticFileDigest,
    UnsupportedSemanticOperationError,
)

__all__ = [
    "AllowlistedCliExecutable",
    "BuildCommand",
    "CliOperationCommand",
    "EvidenceCompleteness",
    "FileRecord",
    "IndexSnapshot",
    "IntelligenceBackendStatus",
    "IntelligenceOperation",
    "IntelligenceProvenance",
    "IntelligenceReadiness",
    "ParseResult",
    "ReadOnlyCliBackendConfig",
    "ReadOnlySemanticCliAdapter",
    "RepositoryEvidence",
    "RepositoryIntelligence",
    "RepositoryIntelligenceQuery",
    "RepositoryIntelligenceResult",
    "RepositoryManifest",
    "SearchHit",
    "SemanticBackendDisabledError",
    "SemanticCliCommandPlan",
    "SemanticExecutionReceipt",
    "SemanticFileDigest",
    "StructuralIndex",
    "StructuralParser",
    "SymbolRecord",
    "UnsupportedSemanticOperationError",
    "build_repository_manifest",
    "collect_project_instructions",
    "discover_instruction_files",
]
